name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
  - aom
  - av
  - blas
  - bzip2
  - ca-certificates
  - colorama
  - cudatoolkit=11.1.1
  - dataclasses
  - expat
  - ffmpeg
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - gettext
  - icu
  - iopath
  - jpeg
  - lame
  - lcms2
  - libffi
  - libiconv
  - libopus
  - libpng
  - libsqlite
  - libtiff
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - numpy
  - numpy-base
  - olefile
  - openh264
  - openssl
  - pip
  - portalocker
  - pthread-stubs
  - python
  - python_abi
  - pytorch=1.9.0
  - six
  - svt-av1
  - tbb
  - tk
  - torchvision=0.10.0
  - tqdm
  - typing_extensions
  - tzdata
  - wheel
  - x264
  - x265
  - xorg-fixesproto
  - xorg-kbproto
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd
  - pip:
    - absl-py
    - antlr4-python3-runtime
    - appdirs
    - beautifulsoup4
    - black
    - blessed
    - cachetools
    - certifi
    - charset-normalizer
    - click
    - cloudpickle
    - contourpy
    - cvxpy
    - cycler
    - decorator
    - decord==0.6.0
    - deepspeed
    - ecos
    - einops
    - filelock
    - fonttools
    - future
    - fvcore
    - gdown
    - google-auth
    - google-auth-oauthlib
    - gpustat
    - grpcio
    - h5py
    - hjson
    - hydra-core
    - idna
    - imageio
    - imageio-ffmpeg
    - importlib-metadata
    - install
    - joblib
    - kiwisolver
    - markdown
    - markupsafe
    - matplotlib
    - moviepy
    - mypy-extensions
    - networkx
    - ninja
    - nvidia-ml-py
    - oauthlib
    - omegaconf
    - opencv-python
    - osqp
    - packaging
    - pandas
    - parameterized
    - pathspec
    - pillow
    - platformdirs
    - proglog
    - protobuf
    - psutil
    - py-cpuinfo
    - pyasn1
    - pyasn1-modules
    - pycocotools
    - pydantic
    - pydot
    - pyparsing
    - pysocks
    - python-dateutil
    - pytz
    - pyyaml
    - qdldl
    - regex
    - requests
    - requests-oauthlib
    - rsa
    - scikit-learn
    - scipy
    - scs
    - seaborn
    - setuptools
    - simplejson
    - soupsieve
    - tabulate
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorboardx
    - termcolor
    - threadpoolctl
    - timm==0.4.12
    - toml
    - tomli
    - torch-ema==0.3
    - urllib3
    - wcwidth
    - werkzeug
    - yacs
    - zipp